IMAGE bga_0 "gfx/0.png" -1
IMAGE bga_1 "gfx/1.png" -1
IMAGE bga_2 "gfx/2.png" -1
IMAGE bga_3 "gfx/3.png" -1
IMAGE bga_4 "gfx/4.png" -1
IMAGE bga_5 "gfx/5.png" -1
IMAGE bga_6 "gfx/6.png" -1
IMAGE bga_7 "gfx/7.png" -1
IMAGE bga_8 "gfx/8.png" -1
IMAGE bga_9 "gfx/9.png" -1
IMAGE bga_gameover "gfx/gameover.png" -1
